[build-system]
requires = ["flit_core >=3.2,<4",
            "myst_parser<=0.18.0",
            "sphinx_rtd_theme>=1.0.0"]
build-backend = "flit_core.buildapi"

[project]
name = "Notes"
authors = [{name = "Anant Singh", email = "anant.singh@nyu.edu"}]
dynamic = ["0.1.0", "Personal Notes"]
